### ISSUE TITLE
Game Freezes when i exit from "My Deck" or "Menu"

### ISSUE THREAD

**Issue by vicksonzero** [jonathan-vallet/js13k-2020#1]
Steps:

1. open new game
2. Battle Mage
3. Click Start Game
4. Click My Deck
5. Click Back

Expected:
back to world map

Actual:
Empty screen with the following console error

Uncaught TypeError: Cannot read property 'classList' of null
    at Le (index.html:formatted:2244)
    at HTMLBodyElement.document.body.onclick (index.html:formatted:2665)
Le @ index.html:formatted:2244
document.body.onclick @ index.html:formatted:2665

**Comment by vicksonzero** [comment]
BTW superb amount of features cramped into 13KB, very well done!

**Comment by jonathan-vallet** [comment]
Hi!
Thank you for you feedbacks! :)

I've fixed some bugs, you can play a fixed version of the game on github pages ( https://jonathan-vallet.github.io/js13k-2020/index.html )

After the contest result, I'll certainly start to develop a real game based on deck building + dice (new graphics and better level design, more stories...). If you are interested you can follow me on twitter ( https://twitter.com/JoeVallet ) I'm not really active, but I'll communicate about that new game in the future :)

**Comment by vicksonzero** [comment]
Still some bugs found after defeating the first encounter. 

Would you rather have me raise them as more bug reports, or wait till you make the next game?

**Comment by jonathan-vallet** [comment]
Hi! it's nice to see someone still playing my little game :)
The desktop version of the game is work in progress but it will take a lot of time. You can report more bugs here, I'll fix them :) (I don't have the 13kb size limitation now! )
